services:
  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    networks:
      - laravel

  data-pasien-service:
    build:
      context: ./data-pasien-service
    container_name: data-pasien-service
    networks:
      - laravel

  farmasi-service:
    build:
      context: ./farmasi-service
    container_name: farmasi-service
    networks:
      - laravel
    environment:
    - IAE_API_KEY=KEY-MHS-157
    - APP_ENV=local

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - appointment-service
      - data-pasien-service
      - farmasi-service
    networks:
      - laravel

networks:
  laravel:
    driver: bridge